project:
  type: website
  output-dir: ../docs

website:
  title: BIDS Projekt
  navbar:
    left:
      - href: index.qmd

format: 
  revealjs:
    footer: Gruppe 3
    theme: white
    height: 100%
    width: 100%
    slide-number: true
    show-slide-number: all
    smaller: true
    scrollable: true
    embed-resources: true
    title-slide-attributes:
      data-background-image: images/title.jpg
      data-background-size: contain

lang: de



